#!/bin/bash
export EPAPER=/Users/hinsen/projects/e-paper

cd $EPAPER/jython-runtime
cp $EPAPER/jars/jython-2.5.2.jar jython-2.5.2-with-runtime.jar
jar uf jython-2.5.2-with-runtime.jar Lib
mv *.jar $EPAPER/jars
