#!/bin/bash
export APAPER=$HOME/projects/e-paper
export ACTIVE_PAPER_LIBRARY=$APAPER/active-paper-library
export RENDERER=$APAPER/markdown-renderer
export BUILD=$RENDERER/build

export JHDF5=${HOME}/Development/cisd-jhdf5/lib/batteries_included/cisd-jhdf5-batteries_included_lin_win_mac.jar

cd $RENDERER
rm -rf build
mkdir build

cd $RENDERER/src
javac -cp $APAPER/jars/markdownj-1.0.2b4-0.3.0.jar:$APAPER/jars/cobra.jar:$APAPER/jars/js.jar:$ACTIVE_PAPER_LIBRARY/active-paper-runtime.jar:$JHDF5 renderer.java
mv renderer.class $BUILD/

cd $BUILD
jar cf $APAPER/jars/markdown-renderer.jar renderer.class
